### PR TITLE
updates to displays

### PR DESCRIPTION
**Pull request by ablwr**
This updates the HTML display for repot-level toggling and test-level detail with arrows. No fancy CSS transformations yet.

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
> No fancy CSS transformations yet.

I miss it! ;-). I like e.g. (google random) [such transformation](http://www.thereconnection.com/faq-practitioner-corner/), with the arrow moving. BTW I also like the less black separation and the color difference between title and cotnent, it may be an idea too.
Also, I think there should be no arrow if "toggle all verbosity" is on because the arrow is no more useful in that case (forced o always open)

**Comment by ablwr** [comment]
I like those arrows too but they are built into Bootstrap (CSS+JS). I will replicate, though!

**Comment by ablwr** [comment]
Please pull the latest and check on the fancy upgrade, and we can chat tomorrow morning/afternoon about upping the fancy level even more.

**Comment by JeromeMartinez** [comment]
On Windows, I have a random display bug when I click on a test in order to see more details then click again on it in order to nest it.

html_display

When I select the "transparent" text, it is black again.

Tested the HTML export in Fireforx or Chrome and it is OK.

**Comment by ablwr** [comment]
@JeromeMartinez Please review and let me know where this is at! This merge needs to be in sync with @dericed's XML update.

**Comment by JeromeMartinez** [comment]
Is fine. @dericed  please push your implementtion XSL update and I merge both PR at the same time.

**Comment by ablwr** [comment]
🎉

**Pull request merged**
