### PR TITLE
add MediaConchSimple display

### PR DESCRIPTION
**Pull request by dericed**

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
` -fs` ==` --format=simple` for the CLI?

**Comment by JeromeMartinez** [comment]
does it make sense to have it in the GUI (which lists only one file at the time, at least for the moment)?

**Comment by dericed** [comment]
I think in the GUI it is okay. Doesn't hurt.

**Comment by JeromeMartinez** [comment]
does it make sense to have it in the GUI (which lists only one file at the time, at least for the moment)?

**Pull request merged**
