### PR TITLE
Make 'or' comparator inclusive

### PR DESCRIPTION
**Pull request by g-maxime**
Signed-off-by: Maxime Gervais <gervais.maxime@gmail.com>

### CODE REVIEW

**Comment by dericed** [comment]
LGTM, but am curious how this came to deviate from https://github.com/MediaArea/MediaConch_SourceCode/blob/a20e2b97f553caa133ab8daf795be90494df9eaa/Tools/Policies/policyset2policytransform2policyresult.xsl#L152.

**Comment by g-maxime** [comment]
@dericed I was looking for this file.

I will check for others missing fixes in the generated file.

**Review by JeromeMartinez — CHANGES_REQUESTED** [review]
Need to sync both the cpp file and the "real source".

**Review by JeromeMartinez — APPROVED** [review]

**Comment by JeromeMartinez** [comment]
> am curious how this came to deviate from 

Am curious too as it is a very bad issue but refrain to spend time in diging in the log.

Files are synced now, we'll add tests for being sure there will be no deviation in the future.

**Pull request merged**
