### PR TITLE
updates for padding and displaying fail/pass

### PR DESCRIPTION
**Pull request by ablwr**
Ah, what I meant to send over this morning. 😅

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
padding is fine now, but I have again (we got it previously but I don't remember when/how it was fixed; there is not this issue without this last commit) the weird issue when I click on the arrow:
- not nested by default
- I click on the arrow, the rule name becomes transparent (or white on white)
- if I select it, black comes back
Happens only inside the software, not if exported and displayed by a browser.

**Comment by ablwr** [comment]
That is a weird bug, I'll try to tidy up the CSS. The default nesting shouldn't be in this PR. Right now it's all running recursively and following the same rules so I have to break the first out of that pattern.

**Comment by JeromeMartinez** [comment]
> The default nesting shouldn't be in this PR

Misunderstanding: it is not nested by default, as before. when I click for nesting, the rule name text color changes to white.

**Comment by ablwr** [comment]
Yeah that's weird and hard to replicate but I'll see if I can fix it. It seemed to be "magic" before, so I will perform "magic" again.

**Comment by ablwr** [comment]
The nesting as you prefer should be added in there and the HTML is valid! 👍

**Comment by ablwr** [comment]
Guess that setting the arrow as "transparent" may be throwing it off, although that seems to be supported widely in browsers, so I changed it to white. Let me know how that looks.

**Comment by JeromeMartinez** [comment]
I still have the issue with the text disappearing.
Other items (type/run/fail/pass hidden etc) are OK.
Still missing:
- if fail and actual value, the value in the main line (after "fail") as in previous version

**Comment by JeromeMartinez** [comment]
>  bases policy outcome on @outcome rather than fail count, shows actual if available at top level fail

Confirmed to work.

**Comment by JeromeMartinez** [comment]
Still the transparency issue :(

**Pull request merged**
