### PR TITLE
Create force option

### PR DESCRIPTION
**Pull request by tribouille**

### CODE REVIEW

**Comment by dericed** [comment]
Is there any versioning if a new analysis is `forced`? Not sure if its needed, but I'm curious if this is considered.

**Comment by JeromeMartinez** [comment]
We plan to force analysis if we change of version (e.g. 16.01 is used now, we know we changed the trace in this version, and trace is from 15.12, so we force the new analysis).
but it will be available only for offcial release (this is the moment we change the version number). If you use nightlies, this will not be automaticly forced, you'll have to do it manually.

**Comment by tribouille** [comment]
Right now, no.
I wrote on the previous report.
It could be done later (I think Jerome has some plan about it).

**Comment by dericed** [comment]
np, force is enough for now

**Pull request merged**
