### PR TITLE
x gcc warnings: -Wunused-parameter

### PR DESCRIPTION
**Pull request by g-maxime**
Signed-off-by: Maxime Gervais <gervais.maxime@gmail.com>

### CODE REVIEW

**Comment by tribouille** [comment]
No, that's the one I want to keep

**Comment by g-maxime** [comment]
Ok

**Comment by JeromeMartinez** [comment]
Let's keep the PR open for the moment, as a big reminder.
But the "final" fix sshould be done not too late, in order not to forget it.

**Comment by JeromeMartinez** [comment]
Resolved with a different method.

**Pull request closed without merging**
