### PR TITLE
Leaner HTML display

### PR DESCRIPTION
**Pull request by ablwr**
screen shot 2016-06-28 at 8 55 19 pm

Attn @JeromeMartinez! This also corrects the title displaying even when empty.

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
I like the condensed output, easier to read without scrolling too much, but with QtWebEngine I have no more the arrow (I can click on a "circle" instead).
new

**Comment by ablwr** [comment]
Oh, I see. I can adjust the width of the arrow. It's built in CSS. I will be able to adjust it this evening (EDT).

**Comment by ablwr** [comment]
I made the arrow smaller, assuming/hoping that that is the issue. If this is something I can replicate on my side, I can test. It's possible that it's a CSS support issue within the WebEngine. But if it was showing an arrow before, it is likely related to sizing.

**Comment by JeromeMartinez** [comment]
Is fine now.
new

**Pull request merged**
