### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by beccabender**

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
Oops. Thanks.
Travis fail is not due to your PR, it is a problem due to a bug in an update on their side, we are working on it before merging.

**Comment by JeromeMartinez** [comment]
@bembleman please rebase in order to get rid from Travis error (due to Travis update, we fixed it in git master)

**Comment by bembleman** [comment]
Just FYI, I'm working with @dericed and he's the one who caught this typo.

**Comment by JeromeMartinez** [comment]
Generated files updated by https://github.com/MediaArea/MediaConch_SourceCode/pull/623.

**Pull request merged**
