### PR TITLE
Must not exist

### PR DESCRIPTION
**Pull request by dericed**
fixes https://github.com/MediaArea/MediaConch_SourceCode/issues/428 and
goes a bit beyond. Now easier to add more operators.

Note if ‘starts with’ or ‘must not start with’, then the value should
not contain a single quote.

Suggestion to proces https://github.com/MediaArea/MediaConch_SourceCode/pull/420 first.

### CODE REVIEW

**Comment by tribouille** [comment]
@GuillaumeRoques you will have to update MCO for the GUI.

> Note if ‘starts with’ or ‘must not start with’, then the value should
> not contain a single quote.
Hmm, that's a hard limitation... Not really good

**Comment by JeromeMartinez** [comment]
is the limitation due to a v1 of the XSL or is it definitive?

**Comment by dericed** [comment]
Possible that I can assess and escape in xsl rather than block in gui

**Comment by dericed** [comment]
This commit is consolidated into https://github.com/MediaArea/MediaConch_SourceCode/pull/420.

**Pull request closed without merging**
