### PR TITLE
toggles verbose view, updates to v0.2 of implementation checker XSL

### PR DESCRIPTION
**Pull request by ablwr**
Related to #273 this adds toggle ability. Right now it's on/off for *everything* but I hope to later make that item-level instead. This also upgrades the display to reflect @dericed's changes in the XML structure for the implementation checker. Jerome, please review!

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
I have an error in some browsers:
"ID implementation-toggle already defined"

an id should be unique.

**Comment by ablwr** [comment]
Updated. Although I still want to move this verbosity toggle to being item-level in the future.

**Comment by JeromeMartinez** [comment]
I like the verbose mode, but (as usual ;-) ):
- implementation check results are ok (1 line per test) if pass, policy check has 2 lines per test if fails

```xml
mp4 wrapper: ❌ fail
Reason: is not equal
```
From my point of view, readability is not good this way.

Would be great to have only one line (`mp4 wrapper: ❌ fail (Reason: is not equal)`) in that case.

- when verbosity is off, this is a bit frustrating not to have the possibility to have verbose info for a specific line (clicking on it would show the verbose mode for this line, clicking again would hide it).
Usually, an user see all results then wants to focus on one line (e;g. the line in error).

**Comment by ablwr** [comment]
Most reasons are longer than one line so it breaks into two lines anyway... but let me know if that's better. I'll get to work on making it item-level but want to get something minimally viable (and stable!) for this upcoming release.

**Comment by JeromeMartinez** [comment]
> Most reasons are longer than one line so it breaks into two lines anyway

Good point.
so request changed to no solid line between "fail" and the reason (only between tests)

**Pull request merged**
